# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "bundle-name-4.1.0" = {
      name = "bundle-name";
      packageName = "bundle-name";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bundle-name/-/bundle-name-4.1.0.tgz";
        sha512 = "tjwM5exMg6BGRI+kNmTntNsvdZS1X8BFYS6tnJ2hdH0kVxM6/eVZ2xy+FqStSWvYmtfFMDLIxurorHwDKfDz5Q==";
      };
    };
    "default-browser-5.4.0" = {
      name = "default-browser";
      packageName = "default-browser";
      version = "5.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/default-browser/-/default-browser-5.4.0.tgz";
        sha512 = "XDuvSq38Hr1MdN47EDvYtx3U0MTqpCEn+F6ft8z2vYDzMrvQhVp0ui9oQdqW3MvK3vqUETglt1tVGgjLuJ5izg==";
      };
    };
    "default-browser-id-5.0.1" = {
      name = "default-browser-id";
      packageName = "default-browser-id";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/default-browser-id/-/default-browser-id-5.0.1.tgz";
        sha512 = "x1VCxdX4t+8wVfd1so/9w+vQ4vx7lKd2Qp5tDRutErwmR85OgmfX7RlLRMWafRMY7hbEiXIbudNrjOAPa/hL8Q==";
      };
    };
    "define-lazy-prop-3.0.0" = {
      name = "define-lazy-prop";
      packageName = "define-lazy-prop";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-lazy-prop/-/define-lazy-prop-3.0.0.tgz";
        sha512 = "N+MeXYoqr3pOgn8xfyRPREN7gHakLYjhsHhWGT3fWAiL4IkAt0iDw14QiiEm2bE30c5XX5q0FtAA3CK5f9/BUg==";
      };
    };
    "is-docker-3.0.0" = {
      name = "is-docker";
      packageName = "is-docker";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-docker/-/is-docker-3.0.0.tgz";
        sha512 = "eljcgEDlEns/7AXFosB5K/2nCM4P7FQPkGc/DWLy5rmFEWvZayGrik1d9/QIY5nJ4f9YsVvBkA6kJpHn9rISdQ==";
      };
    };
    "is-inside-container-1.0.0" = {
      name = "is-inside-container";
      packageName = "is-inside-container";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-inside-container/-/is-inside-container-1.0.0.tgz";
        sha512 = "KIYLCCJghfHZxqjYBE7rEy0OBuTd5xCHS7tHVgvCLkx7StIoaxwNW3hCALgEUjFfeRk+MG/Qxmp/vtETEF3tRA==";
      };
    };
    "is-wsl-3.1.0" = {
      name = "is-wsl";
      packageName = "is-wsl";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-wsl/-/is-wsl-3.1.0.tgz";
        sha512 = "UcVfVfaK4Sc4m7X3dUSoHoozQGBEFeDC+zVo06t98xe8CzHSZZBekNXH+tu0NalHolcJ/QAGqS46Hef7QXBIMw==";
      };
    };
    "open-10.2.0" = {
      name = "open";
      packageName = "open";
      version = "10.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-10.2.0.tgz";
        sha512 = "YgBpdJHPyQ2UE5x+hlSXcnejzAvD0b22U2OuAP+8OnlJT+PjWPxtgmGqKKc+RgTM63U9gN0YzrYc71R2WT/hTA==";
      };
    };
    "run-applescript-7.1.0" = {
      name = "run-applescript";
      packageName = "run-applescript";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-applescript/-/run-applescript-7.1.0.tgz";
        sha512 = "DPe5pVFaAsinSaV6QjQ6gdiedWDcRCbUuiQfQa2wmWV7+xC9bGulGI8+TdRmoFkAPaBXk8CrAbnlY2ISniJ47Q==";
      };
    };
    "wsl-utils-0.1.0" = {
      name = "wsl-utils";
      packageName = "wsl-utils";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wsl-utils/-/wsl-utils-0.1.0.tgz";
        sha512 = "h3Fbisa2nKGPxCpm89Hk33lBLsnaGBvctQopaBSOW/uIs6FTe1ATyAnKFJrzVs9vpGdsTe73WF3V4lIsk4Gacw==";
      };
    };
  };
in
{
  zenn-cli = nodeEnv.buildNodePackage {
    name = "zenn-cli";
    packageName = "zenn-cli";
    version = "0.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/zenn-cli/-/zenn-cli-0.4.0.tgz";
      sha512 = "CRWk+uy/+Mf9kop0iUNNMofUNySt4NFYQ9H6zgmouc/S3ZuqSNJnNmp9DXWQXj0irs+K5DFbzldKsw7ca/1B9Q==";
    };
    dependencies = [
      sources."bundle-name-4.1.0"
      sources."default-browser-5.4.0"
      sources."default-browser-id-5.0.1"
      sources."define-lazy-prop-3.0.0"
      sources."is-docker-3.0.0"
      sources."is-inside-container-1.0.0"
      sources."is-wsl-3.1.0"
      sources."open-10.2.0"
      sources."run-applescript-7.1.0"
      sources."wsl-utils-0.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Preview Zenn content locally.";
      homepage = "https://github.com/zenn-dev/zenn-editor#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
